FROM node:18.14.2-alpine

ARG BUILD_BASE_PATH
ARG FRONTEND_CLIENT_PORT

WORKDIR /app

COPY $BUILD_BASE_PATH/package.json  .

RUN npm install

COPY $BUILD_BASE_PATH/ .
COPY .env .env.production

RUN npm run build

CMD npm start -- -p $FRONTEND_CLIENT_PORT
