FROM node:18-alpine

ARG BUILD_BASE_PATH

# Install necessary build tools
RUN apk add --no-cache python3 make g++

WORKDIR /data

COPY $BUILD_BASE_PATH/package.json  .

RUN npm install

COPY $BUILD_BASE_PATH/ .

CMD [ "npm", "start" ]
